- name: install python3 flask
  package:
    name: 
      - python3-flask
    state: present

- name: allow connection to port 5000 on redhat famillies
  firewalld: 
    port: 5000/tcp
    permanent: true
    state: enabled
  when: ( ansible_os_family == 'RedHat' )

- name: restart firewall
  service:
    name: firewalld
    state: reloaded
  when: ( ansible_os_family == 'RedHat' )

- name: copy prod forwarder.py to /usr/local/bin/
  copy:
    src: forwarder-prod.py
    dest: /usr/local/bin/forwarder.py
    owner: root
    group: root
    mode: 0755
  when: "'Prod' is in group_names"

- name: copy horsprod forwarder.py to /usr/local/bin/
  copy:
    src: forwarder-horsprod.py
    dest: /usr/local/bin/forwarder.py
    owner: root
    group: root
    mode: 0755
  when: "'HorsProd' is in group_names"

- name: push systemd script
  template:
    src: webhook.service.j2
    dest: /etc/systemd/system/webhook.service
    owner: root
    group: root
    mode: 0644

- name: enable webhook service
  service:
    name: webhook
    enabled: yes
    state: restarted

